export const ListOfPlayers =
    [
        {
            id: 1,
            name: 'Faker',
            cost: 20000000,
            club: 'T1',
            img: 'assets/images/faker.jpg',
            info: 'Lee "Faker" Sang-hyeok (Hangul: 이상혁) is a League of Legends esports player, currently mid laner and part owner at T1.',
            clip: 'https://www.youtube.com/embed/97LL8fMc-YI',
        },
        {
            id: 2,
            name: 'Deft',
            cost: 40000000,
            club: 'Dplus KIA',
            img: 'assets/images/deft.jpg',
            info: 'Kim "Deft" Hyuk-kyu (Hangul: 김혁규) is a League of Legends esports player, currently bot laner for Dplus KIA.',
            clip: 'https://www.youtube.com/embed/EvNRwMZQBo8',
        },
        {
            id: 3,
            name: 'Canyon',
            cost: 50000000,
            club: 'Dplus KIA',
            img: 'assets/images/canyon.jpg',
            info: 'Kim "Canyon" Geon-bu (Hangul: 김건부) is a League of Legends esports player, currently jungler for Dplus KIA.',
            clip: 'https://www.youtube.com/embed/F2zzrSsqDzA',
        },
        {
            id: 4,
            name: 'Chovy',
            cost: 220000000,
            club: 'Gen.G',
            img: 'assets/images/chovy.jpg',
            info: 'Jeong "Chovy" Ji-hoon (Hangul: 정지훈) is a League of Legends esports player, currently mid laner for Gen.G. He was previously known as ji hun.',
            clip: 'https://www.youtube.com/embed/WLJNBLDjX4U',
        },
        {
            id: 5,
            name: 'Peanut',
            cost: 90000000,
            club: 'Gen.G',
            img: 'assets/images/peanut.jpg',
            info: 'Han "Peanut" Wang-ho (Hangul: 한왕호) is a League of Legends esports player, currently jungler for Gen.G.',
            clip: 'https://www.youtube.com/embed/yaiua3RFZRE',
        },
        {
            id: 6,
            name: 'Gumayusi',
            cost: 150000000,
            club: 'T1',
            img: 'assets/images/gumayushi.jpg',
            info: 'Lee "Gumayusi" Min-hyeong (Hangul: 이민형) is a League of Legends esports player, currently bot laner for T1. He was previously known as Finale, Catan, and Gumayushi.',
            clip: 'https://www.youtube.com/embed/J2cc2tD11QY',
        },

        {
            id: 7,
            name: 'Zeus',
            cost: 40000000,
            club: 'T1',
            img: 'assets/images/zeus.jpg',
            info: 'Choi "Zeus" Woo-je (Hangul: 최우제) is a League of Legends esports player, currently top laner for T1. He was previously known as Wooje.',
            clip: 'https://www.youtube.com/embed/JNgm3l4Xjh8',
        },

        {
            id: 8,
            name: 'Viper',
            cost: 56020000,
            club: 'Hanwha Life Esports',
            img: 'assets/images/viper.jpg',
            info: 'Park "Viper" Do-hyeon (Hangul: 박도현) is a League of Legends esports player, currently bot laner for Hanwha Life Esports.',
            clip: 'https://www.youtube.com/embed/-1v5Zfn1I58',
        },

        {
            id: 9,
            name: 'Morgan',
            cost: 32000000,
            club: 'Fredit BRION',
            img: 'assets/images/morgan.jpg',
            info: 'Park "Morgan" Ru-han (Hangul: 박루한) is a League of Legends esports player, currently top laner for BRION.',
            clip: 'https://www.youtube.com/embed/TZ-qN-as9LE',
        }
    ];